language: cpp
compiler: gcc
dist: bionic

cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local

addons:
  apt:
    packages:
    - libevent-dev
    # for all EPICS builds
    - libreadline6-dev
    - libncurses5-dev
    - perl
    # for clang compiler
    - clang

install:
  - python .ci/cue.py prepare

script:
  - python .ci/cue.py build
  - python .ci/cue.py test
  - python .ci/cue.py test-results

jobs:
  include:
  - env: BASE=7.0 EXTRA='CMD_CXXFLAGS=-std=c++11 -Wall -Werror'

  - env: BASE=7.0 BCFG=static

  - env: BASE=7.0

  - env: BASE=3.15

  - env: BASE=3.14

  - env: BASE=7.0
    compiler: clang

  - env: BASE=7.0
    dist: trusty
